# Generated by Django 4.2.4 on 2023-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companyusers", "0004_alter_company_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="crunchbase_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="founded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="funding_amt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="funding_rounds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="last_funding_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
