# Generated by Django 4.2.4 on 2023-10-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companyusers", "0005_company_crunchbase_url_company_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
