# Generated by Django 4.2.4 on 2023-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companyusers", "0006_company_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="funding_amt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=30, null=True
            ),
        ),
    ]
